import { DM_Sans } from 'next/font/google';
import './globals.css';

const dmSans = DM_Sans({ subsets: ['latin'], weight: ['400', '500', '600', '700', '800'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [{
    url: '/assets/svg/icon.svg',
  }]
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className='overflow-x-hidden'>
      <body className={` overflow-x-hidden ${dmSans.className}`}>
        {children}
      </body>
    </html>
  );
}
